INSERT INTO roles(name) VALUES('ROLE_COSTUMER');
INSERT INTO roles(name) VALUES('ROLE_RESTAURANT_MANAGER');
INSERT INTO roles(name) VALUES('ROLE_DELIVERY_MAN');
INSERT INTO roles(name) VALUES('ROLE_ADMIN');